---
title: "Description of the Exponential-Logistic Model"
author: "Vassar CogSci Lab Team"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
bibliography: references.bib
output:
  rmarkdown::html_vignette:
    css: stile.css
    toc: false
vignette: >
  %\VignetteIndexEntry{Description of the Exponential-Logistic Model}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  error = TRUE,
  comment = "#>"
)
```

<script type="text/x-mathjax-config">
MathJax.Hub.Config({
  TeX: { equationNumbers: { autoNumber: "AMS" } }
});
</script>

<div id="TOC">
<ul>
<li><a href="#exp">The Experiment (Data Collection)</a></li>
<li><a href="#model">The Model</a></li>
<li><a href="#fits">Sample Fits</a>
<ul>
<li><a href="#fits-sim">Fitting Simulated Data</a></li>
<li><a href="#fits-real">Fitting Real Experimental Data</a></li>
</ul></li>
<li><a href="#references">References</a></li>
</ul>
</div>






The Vassar CogSci Lab is modelling some pretty cool stuff.
<br><br>




# The Experiment (Data Collection) {#exp}
<hr class="sec1">

This is my understanding of how the data were collected in "Experiment 1" from Josh's thesis.

Participants were presented with a sequence of letters moving across window on a computer screen and were supposed to type the letter on the computer's keyboard. The letters appeared animated and moved across the window from right to left, and they were only visible on the screen for two seconds. The response time for each typed letter was bounded below by zero seconds because the timing only started from the moment when the letter first started appearing on the right side of the window, well before the full letter was easily visible. The response times were also bounded above by two seconds because the letters were only visible on the screen for two seconds. In these sequences of letters, there were three different types of three-letter patterns that the participant could encounter. The patterns were sorted by difficulty and classified as one of: easy, three-letter words in the English language; medium, three-letter words in the English language but spelled backwards, or hard, a random permutation of a three-letter English word but was not itself a word in the English language. There was only one intentional pattern in the sequence of letters for each participant, and this pattern would randomly appear approximately seventy times in the sequence throughout the experiment. For more details on the experiment, see @de2016dynamic.

Of particular interest to us are the sequences of response times for the first letter in the pattern and the third letter in the pattern. The idea is that since the first letter in the pattern is randomly placed in the sequence, the participant will exhibit a response time for the first letter that is consistent with their baseline response time for the rest of the random letters in the sequence. If the participant learns the pattern, we expect their response times for the first letter to remain consistent with their response times for the random letters in the sequence; however, we expect their response times for the subsequent letters (in particular the third letter) to decrease as they are able to anticipate this letter and begin to move their finger to the appropriate key before the letter appears on the screen. In the case that te participant does not learn the pattern among the sequence of letters, we expect their response times for every letter in the sequence to be consistent with their baseline response time for the random letters in the sequence. Our main objective with this model is to capture the *possible* decrease in response time for the third letter in the pattern, as this change indicates anticipatory behavior and recognition of the pattern.

Just a quick question about experiment design (because now I'm starting to think about it)- if there were experiment that follows the same setup to this one, but after showing the pattern many times (ideally after the participant learned the pattern, wonder how we could tell if they had!) the third letter in the pattern was changed to something random? I don't know if there's any point in this, but if the response time for the changed letter is higher than that for the baseline random letter would that also demonstrate that the individual had learned the pattern? I'm kinda thinking in the context of a teacher assigning math problems for homework, so maybe it's too different because the "response time" for answering a math problem is likely greater than two seconds. But if you could measure how long it takes a student to do a particular type of problem and give the student a sequence of problems that are all similar, wouldn't we expect to see a decrease in "response time" when the student figures out how to do that type of problem? Then to test if they actually learned the best strategy for solving that type of problem (instead of recognizing the pattern of what to do), the student could then be presented with a slightly different problem that requires a different strategy (perhaps something they haven't learned yet). If the student just recognized the pattern of the previous problems instead of actually learning the material, then I would expect their response time to be consistent with their decreased learned response times (and their answer to be incorrect). On the other hand, if the student has worked out the strategy for the previous type of problem and understands the material, then I would think that their response time should be much greater because they are trying to figure out why their previous strategy doesn't work. Maybe this would be totally infeasible to ask kids to do a ton of math problems even though I'd probably enjoy it, and maybe it doesn't work for a number of other reasons, but I thought I'd ask about it anyway.





# The Model {#model}
<hr class="sec1">

As discussed by @dablander2019bayesian, we treat each response time from each subject to be Log-Normally distributed with parameters $\mu$ and $\sigma$. The Log-Normal distribution has some useful properties for our application, but for extended information on the Log-Normal distribution see [its Wikipedia page](https://en.wikipedia.org/wiki/Log-normal_distribution). Primarily, the Log-Normal distribution has no support for negative response times, yet resembles something of a normal distribution; these properties are consistent with the experimental data. The mean and variance of the distribution are both slightly messy expressions involving both $\mu$ and $\sigma$, but the median of the distribution is a very clean $\exp(\mu)$. We'll exploit this convenience and work directly with the median, and we instead use the transformed parameter $\mu' = \log(\mu)$ so that $\text{median}\big(\text{Log-Normal}(rt | \mu', \sigma)\big) = \exp(\mu') = \exp\big(\log(\mu)\big) = \mu$. We define $\mu'$ as the (log of) mixture of two differentiable (and continuous) functions that can be fully parameterized by seven parameters: $\mu' = \log(f(P, V, E, A, D, L, H))$. These seven parameters are detailed in the list below, including any restrictions on their domains:

\begin{itemize}[label=$\cdot$, itemsep=0pt]
	\item $P \in [0, 1]$ is the probability that the individual learned the pattern during the experiment. If the fitted value of $P$ is close to $1$, that indicates the subject demonstrated recognition of the pattern; however, fitted values of $P$ close to $0$ indicates that the subject failed to recognize the existence of a pattern. Fitted values of $P$ that are neither near $0$ nor $1$ indicate confusion- either in the fitting or the participant during the experiment. Such fitted values of $P$ often occur if the participant shows some consistently low response times after a certain trial, but with sporadic response times consistent with the pre-learning baseline (we had discussed this behavior in our meeting on 29 June 2020). Typical fitted values really vary depending on how consistent the participants' response times are.
	\item $V \in [0, 2]$ represents the median pre-learning response time in seconds; technically, it is the vertical shift of all response times. Naturally, it should not be negative because response times cannot be negative in this experiment. Furthermore, the maximum value is 2 seconds because each letter was only visible in the window for 2 seconds before the next letter appeared and the response time was cut off. Typical fitted values are around $1$ second.
	\item $E \in [0, \infty)$ is the overall scale of the exponential used to model the period of adaptation to the task. It must be nonnegative because it must be monotonically decreasing as the subject gets used to the experiment. Typical fitted values are somewhere around $0.3$.
	\item $A \in [0, \infty)$ is the adaptation rate to the task. It again must be nonnegative so that the exponential term decays instead of grows. Typical fitted values are somewhere around $0.3$.
	\item $D \in [0, 1]$ is the scale of the learning "drop." It is the scaled difference between the mean pre-learning response time and the mean post-learning response time. A value near $0$ indicates a small decrease in response time (a post-learning response time the same as that of the pre-learning); a value near $1$ indicates a massive decrease in response time (a post-learning response time of $0$). Note that $D$ is basically meaningless if learning does not occur, that is, if $P$ is near $0$. Typically we observe fitted values around $0.4$ for a participant who demonstrated learning behavior in the experiment.
	\item $L \in [0, \infty)$ is the learning rate of the subject. A negative learning rate would cause the logistic part of the expression to increase rather than decrease. Again, if $P$ is near $0$, $L$ has little meaning. Fitted values for this parameter vary a lot because the decrease in response times tend to happen over one trial (the response times decrease instantly as soon as the participant recognizes the pattern). Since the learning does not happen gradually, the fitted values for this parameter are likely not too useful for this experiment.
	\item $H \in [0, n]$, is the onset of learning, where $n$ is the number of trials performed in the experiment by the individual. $H$ represents how many trials it takes for the subject to learn the pattern, and again has little meaning if $P$ is near $0$. Fitted values for $H$ really vary by individual and pattern difficulty- easier patterns are recognized earlier than more difficult patterns.
	\item $\sigma \in [0, \infty)$ drives the variance in the response times more than $\mu'$, so we treat it as a proxy for the variance; naturally, it should be nonnegative.
\end{itemize}

With those definitions in order, the model for a single subject is shown below:

\begin{equation} \label{eqn:model}
\begin{aligned}
rt &\sim \text{Log-Normal}(\mu', \sigma),\\[2ex]
\mu' &= \log\big( P \cdot \gamma_1 + (1-P) \cdot \gamma_0 \big),\\[2ex]
\gamma_1 &= \Big( V + E \cdot \exp(-A \cdot t) \Big) \cdot \bigg( 1 - \frac{D}{1+\exp(-L \cdot (t-H))} \bigg),\\
\gamma_0 &= V + E \cdot \exp(-A \cdot t),
\end{aligned}
\end{equation}
where $t$ is the trial iteration, $t \in \{1, \dots, n\}$, and $n$ is the number of trials performed in the experiment. The case where the participant learns the pattern is provided by $\gamma_1$, and $\gamma_0$ represents the participant failing to learn the pattern.

Note that you can rewrite the expression for $\mu'$ and simplify it slightly. However, this simplification results in $\Big( V + E \cdot \exp(-A \cdot t) \Big) \bigg( 1 - \frac{P \cdot D}{1+\exp(-L \cdot (t-H))} \bigg)$, where the parameters $P$ and $D$ essentially merge into one parameter that combines the probability of learning and the scale of the decrease in response time. Combining these two parameters into one could be another way to model this behavior, but I think they lose their interpretability this way. I prefer to have two interpretable parameters rather than one confusing parameter, so I would suggest using the original formulation to keep $P$ and $D$ separate.

Since we have some pertinant information and beliefs as to what these parameters should be, we place priors on them. For the most part these priors will be only weakly informative because we want the data to primarily drive the fitting, but there are a few exceptions. For $P$, the probability of learning, we would ideally like this to be binary; however, Stan cannot handle discrete parameters in its models so we settle for a very, very sharp Beta prior. The hyperparameters for this prior strongly suggest that the probability of learning be as close to either $0$ or $1$ as possible.

The hyperprior for $D$, the scale of the decrease in response time, was originally going to be pushed strongly away from zero in an effort to avoid fitting non-learners with a $P$ near $1$ and a $D$ near $0$. With the strong prior on $P$, this turned out to be unnecessary so I left the prior on $D$ to be somewhat informative- it discourages values near $0$ or $1$ because neither is particularly likely/useful.

The priors on $E$ and $A$ are nothing special because I was more focused on the classification of learners vs non-learners and the characterization of when the learning occurs. As a result, these parameters are stuck with some simple Gamma priors. The other priors and hyperpriors are mostly weakly informative Cauchy distributions; this is similar to a normal distribution but with a fatter tail so that the data drives the fitting more than the prior. The distributions of all of the priors and hyperpriors for the model parameters and hyperparameters are shown below:

\begin{equation} \label{eqn:hier}
  \begin{aligned}
    P &\sim \text{Beta}(0.05, 0.05),\\[0.25ex]
    V &\sim \text{Gamma}(v_\alpha, v_\beta),\\[0.15ex]
    &\hspace{5mm} v_\alpha \sim \text{Cauchy}(2.5, 1),\\[0.15ex]
    &\hspace{5mm} v_\beta \sim \text{Cauchy}(1.75, 1),\\[0.25ex]
    E &\sim \text{Gamma}(2.5, 10),\\[0.25ex]
    A &\sim \text{Gamma}(2.5, 10),\\[0.25ex]
    D &\sim \text{Beta}(d_\alpha, d_\beta),\\[0.15ex]
    &\hspace{5mm} d_\alpha \sim \text{Cauchy}(2.5, 1),\\[0.15ex]
    &\hspace{5mm} d_\beta \sim \text{Cauchy}(2.5, 1),\\[0.25ex]
    L &\sim \text{Gamma}(\ell_\alpha, \ell_\beta),\\[0.15ex]
    &\hspace{5mm} \ell_\alpha \sim \text{Cauchy}(4, 1),\\[0.15ex]
    &\hspace{5mm} \ell_\beta \sim \text{Cauchy}(10, 1),\\[0.25ex]
    H &\sim \text{Cauchy}(h_\text{loc}, h_\text{scale}),\\[0.15ex]
    &\hspace{5mm} h_\text{loc} \sim \text{Cauchy}(\tfrac{n}{2}, 1),\\[0.25ex]
    &\hspace{5mm} h_\text{scale} \sim \text{Cauchy}(25, 1),\\[0.15ex]
    \sigma &\sim \text{Gamma}(2, 10).\\
  \end{aligned}
\end{equation}





# Sample Fits {#fits}
<hr class="sec1">

These are sample fits using the model. We'll show simulated data and real data collected from the experiment




## Fitting Simulated Data {#fits-sim}

Basically just checking to make sure that the model recovers the parameters




## Fitting Real Experimental Data {#fits-real}

Now using the model to fit data from the experiment.







</div>





# References
